### ISSUE TITLE
crash on Windows 10 platform

### ISSUE THREAD

**Issue by qlahcim** [JimHokanson/plotBig_Matlab#16]
After run robo_test.m on Windows 10Pro (+MATLAB R2018a) I always got the attached crash report.

[crash.txt](https://github.com/JimHokanson/plotBig_Matlab/files/2087298/crash.txt)

**Comment by JimHokanson** [comment]
My tests need to be cleaned up and that file is old and shouldn't be used. 

I currently prefer the following function and params:

```
s1 = big_plot_tests.speed.s001_speed_test_1('n_samples',[1e5 1e6 1e7 5e7 1e8 2e8]);
```

The crash file lists your processor as:
x86 Family 6 Model 30 Stepping 5

Which from this:
http://www.speedtraq.com/

I take as being:
https://ark.intel.com/products/48496/Intel-Core-i5-760-Processor-8M-Cache-2_80-GHz

If this is accurate then this is and older processor with only SSE4.2 and older support (not AVX or AVX2)

So either:
1. My AVX check is failing and you're trying to call functionality on your processor that doesn't exist
2. I am using some SSE4.2 code that has a bug in it
3. There is some other bug

Can you run the following command and let me know what it says?

```
big_plot.simdCheck
```

Alternatively, you can try compiling the code yourself. I've been updating the the compiling code but check out:
https://github.com/JimHokanson/plotBig_Matlab/blob/master/documentation/how_to_compile.md

Importantly for your case you should probably disable SIMD `USE_SIMD=0` in `compile2.m`

**Comment by qlahcim** [comment]
OK … function `compile2.m` works well for me. Thanks!!
