### ISSUE TITLE
Unknown bug

### ISSUE THREAD

**Issue by riccardogiro** [JimHokanson/plotBig_Matlab#29]
Script and data [here](https://drive.google.com/drive/folders/1gNH2G3nkNWoqDugXeD-PEBjqLSRMQfxS?usp=sharing).
Output of the script:
![image](https://user-images.githubusercontent.com/60734967/143678813-4adfa86a-85ed-4582-8d37-cb85cc19f5c4.png)

**Comment by JimHokanson** [comment]
Thanks Riccardo. I saw this and will try and look at it tomorrow. It looks like it should be a simple fix, unlike the last bug we ran into.

**Comment by JimHokanson** [comment]
Should be fixed ... Just pushed an update. The new code I wrote to fix the last bug had its dimensions reversed. This worked fine for 1 channel but fails for multiple channels (may have actually failed silently for 2 channels, failed explicitly for 3+). Please verify OK behavior.

**Comment by riccardogiro** [comment]
Perfect, it works great! Bug fixed.
Thanks Jim!
