### ISSUE TITLE
bug in reduceToWidth.m line 327-328 

### ISSUE THREAD

**Issue by diedriam** [JimHokanson/plotBig_Matlab#30]
I tracked down an error in lines 279-328 "elseif isobjext(x)
if x is not object then 
1) x_start, x_stop are not getting a value assigned.  add->  x_tstart = x(I1); x_tstop = x(I2);
2) line 327 "x_Istart = x(I1)" is wrong. change to -> x_Istart = I1;
3) line 328 "x_Istop = x(I2);" is wrong. change to -> x_Istop = I2;

-----------
279 elseif isobject(x)

317 else 

327     %x_Istart = x(I1);
328     %x_Istop = x(I2);

% need to be changed to:
           x_tstart = x(I1);
           x_tstop = x(I2);
           x_Istart = I1;
           x_Istop = I2;

330 end
------------

**Comment by JimHokanson** [comment]
Great, thanks! I updated the code as suggested. 

Note to self, reproduction of bug added to previous bugs pb009 in testing suite
